# Generated by Django 4.0.5 on 2022-06-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandF', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lost',
            name='contact',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='lost',
            name='description',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='lost',
            name='name',
            field=models.CharField(default='None', max_length=15),
        ),
        migrations.AddField(
            model_name='lost',
            name='picture',
            field=models.ImageField(default='None', upload_to='media'),
        ),
    ]
