# Generated by Django 4.0.5 on 2022-06-28 08:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LandF', '0002_lost_contact_lost_description_lost_name_lost_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='lost',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
